GET http://localhost:3000

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### FIND SONGS REQUEST
GET http://localhost:3000/songs/test

### CREATE SONG REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "New Song",
    "artists": ["New Artist"],
    "releaseDate": "2021-01-01",
    "duration": "01:00"
}


### UPDATE SONG REQUEST
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
  "title": "Updated Song",
  "artist": "Updated Artist",
  "genre": "Updated Genre"
}

### DELETE SONG REQUEST
DELETE http://localhost:3000/songs/1

